version: "3"

networks:
    proxy:
        external: true

services:
    client:
        container_name: client
        image: node:14.0.0
        user: node
        stdin_open: true
        tty: true
        working_dir: /home/node
        networks:
            - proxy
        volumes:
            - .:/home/node
