version: "3"

networks:
    proxy:
        external: true

services:
    database:
        image: postgres:13.1
        networks:
            - proxy
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: database
        volumes:
            - ./data:/var/lib/postgresql/data
