version: "3"

networks:
    default:
        name: proxy

services:
    proxy:
        image: nginx:1.19.6
        ports:
            - 80:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
